name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  pull_request_target:
    types:
        - opened
    branches:
          - '*/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Install Playwright browsers
        run: yarn playwright install

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn prettier

      - name: Run all Playwright tests
        run: yarn test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Publish Playwright HTML Report to PR
        if: always() && github.event_name == 'pull_request'
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'playwright-report/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: 'Playwright Test Report'